apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: manifest
  namespace: argo-cd
spec:
  project: default
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/kazu728/manifest
    targetRevision: HEAD
    path: k8s
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
