tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
brew "act"
brew "anyenv"
brew "augeas"
brew "python@3.9"
brew "awscli"
brew "bat"
brew "certbot"
brew "cheat"
brew "deno"
brew "docker-clean"
brew "exa"
brew "fzf"
brew "gawk"
brew "gh"
brew "ghq"
brew "gibo"
brew "gnu-sed"
brew "grep"
brew "hadolint"
brew "hub"
brew "hugo"
brew "jq"
brew "lazydocker"
brew "lazygit"
brew "mas"
brew "mkcert"
brew "nkf"
brew "peco"
brew "percona-toolkit"
brew "procs"
brew "protobuf"
brew "pulumi"
brew "qemu"
brew "tfenv"
brew "tmux"
brew "tree"
brew "yarn"
cask "alfred"
cask "android-file-transfer"
cask "appcleaner"
cask "bitwarden"
cask "chromium"
cask "clipy"
cask "cloudflare-warp"
cask "coteditor"
cask "cyberduck"
cask "deepl"
cask "discord"
cask "docker"
cask "drawio"
cask "dropbox"
cask "figma"
cask "firefox"
cask "geekbench"
cask "google-chrome"
cask "google-chrome-canary"
cask "google-cloud-sdk"
cask "grammarly"
cask "ip-in-menu-bar"
cask "iterm2"
cask "karabiner-elements"
cask "kindle"
cask "mysqlworkbench"
cask "ngrok"
cask "postman"
cask "slack"
cask "spectacle"
cask "spotify"
cask "tableplus"
cask "utm"
cask "virtualbox"
cask "visual-studio-code"
cask "wireshark"
cask "zeplin"
mas "Be Focused", id: 973134470
mas "GarageBand", id: 682658836
mas "Hex Fiend", id: 1342896380
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "LINE", id: 539883307
mas "Messenger", id: 1480068668
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Pine Player", id: 1112075769
mas "Times", id: 1048770312
mas "Xcode", id: 497799835
