tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
brew "anyenv"
brew "bat"
brew "certbot"
brew "cheat"
brew "deno"
brew "docker-clean"
brew "exa"
brew "fd"
brew "fzf"
brew "ghq"
brew "gibo"
brew "grep"
brew "hub"
brew "hugo"
brew "jq"
brew "lazydocker"
brew "lazygit"
brew "mas"
brew "mkcert"
brew "nkf"
brew "peco"
brew "percona-toolkit"
brew "procs"
brew "tfenv"
brew "tmux"
brew "tree"
brew "yarn"
cask "alfred"
cask "android-file-transfer"
cask "appcleaner"
cask "authy"
cask "chromium"
cask "clipy"
cask "coteditor"
cask "cyberduck"
cask "deepl"
cask "discord"
cask "docker"
cask "drawio"
cask "dropbox"
cask "figma"
cask "firefox"
cask "geekbench"
cask "google-chrome"
cask "google-cloud-sdk"
cask "grammarly"
cask "ip-in-menu-bar"
cask "iterm2"
cask "karabiner-elements"
cask "kindle"
cask "mysqlworkbench"
cask "ngrok"
cask "postman"
cask "slack"
cask "spectacle"
cask "spotify"
cask "tableplus"
cask "virtualbox"
cask "visual-studio-code"
cask "wireshark"
cask "zeplin"
mas "Be Focused", id: 973134470
mas "GarageBand", id: 682658836
mas "Hex Fiend", id: 1342896380
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "LINE", id: 539883307
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Pine Player", id: 1112075769
mas "Xcode", id: 497799835
