tap "helix-editor/helix"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "ktr0731/evans"
brew "act"
brew "anyenv"
brew "augeas"
brew "python@3.9"
brew "awscli"
brew "bat"
brew "certbot"
brew "deno"
brew "docker-clean"
brew "exa"
brew "freetds"
brew "gawk"
brew "gh"
brew "ghq"
brew "gibo"
brew "gnu-sed"
brew "unbound"
brew "gnutls"
brew "go"
brew "golangci-lint"
brew "grep"
brew "hadolint"
brew "hub"
brew "hugo"
brew "jq"
brew "krb5"
brew "lazydocker"
brew "lazygit"
brew "mas"
brew "mkcert"
brew "nghttp2"
brew "nkf"
brew "peco"
brew "percona-toolkit"
brew "postgresql"
brew "procs"
brew "protobuf"
brew "qemu"
brew "sops"
brew "terraformer"
brew "tfenv"
brew "tmux"
brew "tree"
brew "yarn"
brew "helix-editor/helix/helix"
brew "ktr0731/evans/evans"
cask "adobe-acrobat-reader"
cask "alfred"
cask "android-file-transfer"
cask "appcleaner"
cask "bitwarden"
cask "bluesnooze"
cask "clipy"
cask "cloudflare-warp"
cask "coteditor"
cask "cyberduck"
cask "deepl"
cask "discord"
cask "docker"
cask "drawio"
cask "figma"
cask "firefox"
cask "google-chrome"
cask "google-chrome-canary"
cask "google-cloud-sdk"
cask "google-drive"
cask "grammarly"
cask "ip-in-menu-bar"
cask "iterm2"
cask "karabiner-elements"
cask "kindle"
cask "multipass"
cask "mysqlworkbench"
cask "notion"
cask "postman"
cask "responsively"
cask "slack"
cask "spectacle"
cask "tableplus"
cask "toggl-track"
cask "virtualbox"
cask "visual-studio-code"
cask "visual-studio-code-insiders"
cask "wireshark"
mas "GarageBand", id: 682658836
mas "Gifski", id: 1351639930
mas "Hex Fiend", id: 1342896380
mas "Keynote", id: 409183694
mas "LINE", id: 539883307
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Pine Player", id: 1112075769
mas "Times", id: 1048770312
mas "WebP Converter", id: 1522368690
