repositories:
- name: argo
  url: https://argoproj.github.io/argo-helm

releases:
- name: argo-cd
  namespace: argo-cd
  chart: argo/argo-cd
  version: 7.8.7
  timeout: 600
  wait: true
  values:
  - values.yaml
